### ISSUE TITLE
Support partial loading by key prefix 

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf#304]
If we support defining a group of data search attributes by prefix

**Comment by longquanzheng** [comment]
This can be done by using the existing schema:
```
        partialLoadingKeys:
          type: array
          items:
            type: string
        lockingKeys:
          type: array
          items:
            type: string
```
Basically the keys can mean "prefix"
