### ISSUE TITLE
Docker compose is flaky with Cadence using Kafka, probably just upgrade Cadence

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf#458]
by @lwolczynski : seems like the Kafka is sometimes not ready on the first time, and it will work on 2nd run.

Our Cadence dependencies are too old, maybe just upgrade it

**Comment by longquanzheng** [comment]
The issue is that Kafka is depends on Zookeeper, Cadence depends on Kafka.
Sometimes Kafka is started earlier than zookeeper then run into problems

**Comment by longquanzheng** [comment]
ChatGPT told us this solution:
```
version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "sh", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
```
